[package]
name = "playlie"
version = "0.1.0"
authors = ["Sebastian Nowicki <sebnow@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = {version = "^0.11.0", features=["json"]}
serde = {version = "^1.0", features=["derive"]}
serde_json = "^1.0"
tokio = {version = "^1.0.2", features=["full"]}
